bases:
    -   ../../base
patchesJson6902:
    -   target:
            group: apps
            version: v1
            kind: Deployment
            name: webserver-php-fpm
        path: ./webserver-php-fpm-patch.yml