front_cart:
    path: /warenkorb/
    defaults: { _controller: ShopsysShopBundle:Front\Cart:index }

front_customer_edit:
    path: /kunde/angaben-bearbeiten/
    defaults: { _controller: ShopsysShopBundle:Front\Customer:edit }

front_customer_orders:
    path: /kunde/bestellungen/
    defaults: { _controller: ShopsysShopBundle:Front\Customer:orders }

front_customer_order_detail_registered:
    path: /kunde/bestellungen/detail/{orderNumber}
    defaults: { _controller: ShopsysShopBundle:Front\Customer:orderDetailRegistered }

front_customer_order_detail_unregistered:
    path: /bestelldetails/{urlHash}
    defaults: { _controller: ShopsysShopBundle:Front\Customer:orderDetailUnregistered }

front_login:
    path: /anmelden/
    defaults: { _controller: ShopsysShopBundle:Front\Login:login }

front_logout:
    path: /abmelden/{_csrf_token}
    # controller's action is unnecessary, because firewall processes whole request

front_order_index:
    path: /bestellung/
    defaults: { _controller: ShopsysShopBundle:Front\Order:index }

front_order_paid:
    path: /order-paid/{urlHash}
    defaults: { _controller: ShopsysShopBundle:Front\Order:paid }

front_order_not_paid:
    path: /order-not-paid/{urlHash}
    defaults: { _controller: ShopsysShopBundle:Front\Order:notPaid }

front_order_sent:
    path: /bestellung-bestatigen/
    defaults: { _controller: ShopsysShopBundle:Front\Order:sent }

front_product_search:
    path: /suchen/
    defaults: { _controller: ShopsysShopBundle:Front\Product:search }

front_registration_register:
    path: /registration/
    defaults: { _controller: ShopsysShopBundle:Front\Registration:register }

front_registration_reset_password:
    path: /vergessenes-passwort/
    defaults: { _controller: ShopsysShopBundle:Front\CustomerPassword:resetPassword }

front_registration_set_new_password:
    path: /neues-passwort/
    defaults: { _controller: ShopsysShopBundle:Front\CustomerPassword:setNewPassword }

front_brand_list:
    path: /brand-ubersicht/
    defaults: { _controller: ShopsysShopBundle:Front\Brand:list }

front_personal_data:
    path: /personliche-informationen-ubersicht/
    defaults: { _controller: ShopsysShopBundle:Front\PersonalData:index }

front_personal_data_access:
    path: /personliche-informationen-ubersicht/{hash}/
    defaults: { _controller: ShopsysShopBundle:Front\PersonalData:accessDisplay }

front_personal_data_export:
    path: /personliche-informationen-export/
    defaults: { _controller: ShopsysShopBundle:Front\PersonalData:export }

front_personal_data_access_export:
    path: /personliche-informationen-export/{hash}/
    defaults: { _controller: ShopsysShopBundle:Front\PersonalData:accessExport }

front_store_index:
    path: /stores/
    defaults: { _controller: ShopsysShopBundle:Front\Store:index }

front_store_detail:
    path: /stores/detail/{storeId}/
    defaults: { _controller: ShopsysShopBundle:Front\Store:detail }
