services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shopsys\ShopBundle\Model\Feed\HsSport\HsSportFeedInfo: ~

    Shopsys\ShopBundle\Model\Feed\HsSport\HsSportFeed:
        tags:
          - { name: shopsys.product_feed }
